debug: true

environment: local

server:
  address: :5000

db:
  host: localhost
  port: 5432
  user: postgres
  password: password
  name: chat
  ssl_mode: disable
  max_open_conns: 20
  max_idle_conns: 5

jwt:
  secret_key: replace_me
  expiry_seconds: 999999999

gnatsd:
  log: true
  debug: false
  trace: false
  url: nats://localhost:4222
